### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by NaoyaNemezawa** [NaoyaNemezawa/protospace-32981#1]
#URL
https://protospace-32981.herokuapp.com/

**Comment by TECHCAMP555** [comment]
NaoyaNemezawaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・正しくフォームを入力すると、コメントが投稿できること
コメントを送信すると画像のようなエラーが出てしまします。
<img width="782" alt="スクリーンショット 2020-12-16 11 08 50" src="https://user-images.githubusercontent.com/69237012/102296019-db79d500-3f8f-11eb-8aba-3a986a79654e.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by NaoyaNemezawa** [comment]
ご確認ありがとうございます。

内容を修正いたしましたので再度ご確認をお願いします。

**Comment by TECHCAMP555** [comment]
NaoyaNemezawa さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
